### ISSUE TITLE
UnexpectedTagNameException selenium.common.exceptions.UnexpectedTagNameException: Message: Select only works on <select> elements, not on app-tooltip

### ISSUE THREAD

**Issue by DestoGit** [FabianStammen/ForexFactoryScraper#10]
Hi, thanks for the script.
I'm interested in using your code mainly to retrieve the "impact" info from ForexFactory with monthly url
as for example
https://www.forexfactory.com/calendar?month=jul.2023

I'm getting this error.
Is it due to some ForexFactory site changes?

thanks for your remarks or update suggestions.

```
GitT MINGW64 /c/ForexFactoryScraper
$ python ffs.py
Traceback (most recent call last):
  File "C:\ForexFactoryScraper\ffs.py", line 239, in <module>
    scrap(gettz('UTC-5'))  # HistData saves its Forex data with UTC-5
  File "C:\ForexFactoryScraper\ffs.py", line 66, in scrap
    ff_timezone = get_timezone(driver)
  File "C:\ForexFactoryScraper\ffs.py", line 52, in get_timezone
    select = Select(WebDriverWait(driver, 10).until(
  File "C:\ForexFactoryScraper\virt\lib\site-packages\selenium\webdriver\support\select.py", line 39, in __init__
    raise UnexpectedTagNameException(f"Select only works on <select> elements, not on {webelement.tag_name}")
selenium.common.exceptions.UnexpectedTagNameException: Message: Select only works on <select> elements, not on app-tooltip
```

Also I had to use 

`import undetected_chromedriver as uc`

 as the repo new script use
 
 https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/example/example.py

**Comment by dadlobster** [comment]
Same issues and tried on two different devices

**Comment by FabianStammen** [comment]
Probably some Site Changes, gonna have a look into if you still need it, Else I would Mark it as depricated
